name: neteye.pcs
description: Ansible NetEye PCS collection.
is_template: false
archived: false
template:
  owner: neteye-platform
  repository: default-repository-template
  include_all_branches: false

branch_rulesets:
  main-branch-protection:
    rules:
      required_status_checks:
        required_check:
          - context: "Tests"
            integration_id: 15368 # GH Actions
