name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "*"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@9f08574aec4f15aeb1011090bb102bea0ef2b60c # main
    secrets: inherit
