name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@740d307f524f37043030b6786c4d6a08897bd615 # main
    secrets: inherit
