name: Common Manual Checks

on:
  workflow_dispatch:

permissions: write-all

jobs:
  common-manual-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-manual-checks.yaml@main
    secrets: inherit
