name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "*"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@fba46dd01055d83d308f05d78cdd3cf4bcdf49ce # main
    secrets: inherit
