name: Generate Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "Matrix for Terragrunt jobs"
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check for duplicate teams and repository names
        run: |
          set -euo pipefail

          team_duplicates=$(
            yq --no-doc '.name' teams/teams/*.yaml \
            | sort \
            | uniq -d
          )

          repository_duplicates=$(
            yq --no-doc '.name' repositories/*/repos/*.yaml \
            | sort \
            | uniq -d
          )

          if [ -n "$team_duplicates" ]; then
            echo "Duplicate team names found:"
            echo "$team_duplicates"
            exit 1
          fi

          if [ -n "$repository_duplicates" ]; then
            echo "Duplicate repository names found:"
            echo "$repository_duplicates"
            exit 1
          fi

      - name: Create matrix for Terraform plan
        id: create-matrix
        run: |
          repo_categories_folders=$(find repositories -mindepth 1 -maxdepth 1 -type d | jq -R -s -c 'split("\n")[:-1]')
          units=$(jq -cn \
            --arg teams "teams" \
            --arg org "org-settings" \
            --argjson repos "$repo_categories_folders" \
            '[$teams, $org] + $repos')
          echo "matrix={\"unit\": $units}" >>"$GITHUB_OUTPUT"
