name: Terragrunt Plan

on:
  pull_request:
    branches:
      - "main"

jobs:
  generate-matrix:
    permissions:
      contents: read
    uses: ./.github/workflows/generate-matrix.yaml

  terragrunt-plan:
    needs: generate-matrix
    permissions:
      contents: read
    uses: ./.github/workflows/plan-core.yaml
    with:
      matrix: ${{ needs.generate-matrix.outputs.matrix }}
      neteye_manager_app_id: ${{ vars.NETEYE_MANAGER_APP_ID }}
      neteye_app_id: ${{ vars.NETEYE_APP_ID }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BILLING_EMAIL: ${{ secrets.BILLING_EMAIL }}
      NETEYE_MANAGER_APP_PRIVATE_KEY: ${{ secrets.NETEYE_MANAGER_APP_PRIVATE_KEY }}
      NETEYE_APP_PRIVATE_KEY: ${{ secrets.NETEYE_APP_PRIVATE_KEY }}

  terragrunt-plan-success:
    name: Terragrunt Plan Success
    needs: terragrunt-plan
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "All plan jobs completed successfully!"
